### ISSUE TITLE
Changing App Theme using ServiceUtils

### ISSUE THREAD

**Issue by DarkNormal** [Heromine/Service-Notes#8]
Using the answer from matiash [about changing the status bar color](http://stackoverflow.com/a/26749343/3042873), I added a Window parameter to the setSavedTheme method, which is passed in from each activity

```
Window window = getWindow();
ServiceUtils.setSavedTheme(this, window);
```

Using this window variable, the statusBarColor can be changed using the following code in each switch statement, changing the colorPrimaryDark to suit each case.

```
window.setStatusBarColor(ContextCompat.getColor(context,R.color.colorPrimaryDark));
```

You might be able to pass an Activity reference to the method rather than Context + Window but this solution should work, the only downside is that any activity in the background stack will have the original colorPrimaryDark for a fraction of a second before being set.

So my setSavedTheme method is similar to this

```
public static void setSavedTheme(Context context, Window window) {
    SharedPreferences sharedPrefs = PreferenceManager.getDefaultSharedPreferences(context);
    String theme = sharedPrefs.getString("selected_theme", "0");
    try {
        int themeNumber = Integer.parseInt(theme);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);

        }
        switch (themeNumber) {
            case 0:
                context.setTheme(R.style.MyAppTheme);
                window.setStatusBarColor(ContextCompat.getColor(context,R.color.colorPrimaryDark));
                break;
            case 1:
                context.setTheme(R.style.MyAppTheme2);
                window.setStatusBarColor(ContextCompat.getColor(context,R.color.colorPrimaryDark2));
                break;
```

etc.

**Comment by Heromine** [comment]
But in this way there is not the Window window in all the activities

**Comment by JonathanImperato** [comment]
OK, ok,  maybe it is better your way :P

**Comment by DarkNormal** [comment]
It isn't a perfect fix as I said because it defaults to the theme set in the Manifest, there might be an easier way to do it. I only tested this on a 5.1.1 device too, I don't know how it works below that. AppCompat probably has a solution :)

**Comment by JonathanImperato** [comment]
Before i find it, i'll set this.
Thank you!
